In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('sample.csv')

In [4]:
df

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
96,13/07/2020 19:56:49,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,13/07/2020 21:21:42,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,13/07/2020 21:22:56,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
99,13/07/2020 21:23:57,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No
100,18/07/2020 20:16:21,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    object
 1   Choose your gender                            101 non-null    object
 2   Age                                           100 non-null    float64
 3   What is your course?                          101 non-null    object
 4   Your current year of Study                    101 non-null    object
 5   What is your CGPA?                            101 non-null    object
 6   Marital status                                101 non-null    object
 7   Do you have Depression?                       101 non-null    object
 8   Do you have Anxiety?                          101 non-null    object
 9   Do you have Panic attack?                     101 non-null    object
 10  Did you seek any specialist for a treatment?  101 non-null    object
dtypes: float64(1), object(10)
memory usage: 4.8+ KB

In [6]:
z=df[['Age','What is your CGPA?']]

In [7]:
df.Timestamp

0           8/7/2020 12:02
1           8/7/2020 12:04
2           8/7/2020 12:05
3           8/7/2020 12:06
4           8/7/2020 12:13
              ...
96     13/07/2020 19:56:49
97     13/07/2020 21:21:42
98     13/07/2020 21:22:56
99     13/07/2020 21:23:57
100    18/07/2020 20:16:21
Name: Timestamp, Length: 101, dtype: object

In [8]:
z

      Age What is your CGPA?
0    18.0        3.00 - 3.49
1    21.0        3.00 - 3.49
2    19.0        3.00 - 3.49
3    22.0        3.00 - 3.49
4    23.0        3.00 - 3.49
..    ...                ...
96   21.0        3.50 - 4.00
97   18.0        3.00 - 3.49
98   19.0        3.50 - 4.00
99   23.0        3.50 - 4.00
100  20.0        3.00 - 3.49

[101 rows x 2 columns]

In [10]:
df.Timestamp.min()

'13/07/2020 10:07:32'

In [12]:
df.Timestamp.max()

'9/7/2020 6:57'

In [13]:
df.notnull()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
96,True,True,True,True,True,True,True,True,True,True,True
97,True,True,True,True,True,True,True,True,True,True,True
98,True,True,True,True,True,True,True,True,True,True,True
99,True,True,True,True,True,True,True,True,True,True,True
100,True,True,True,True,True,True,True,True,True,True,True

In [15]:
x=pd.notnull(df["Marital status"])

In [16]:
x

0      True
1      True
2      True
3      True
4      True
       ...
96     True
97     True
98     True
99     True
100    True
Name: Marital status, Length: 101, dtype: bool

In [19]:
y=df.fillna(df.Timestamp.min())

In [20]:
y

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
96,13/07/2020 19:56:49,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,13/07/2020 21:21:42,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,13/07/2020 21:22:56,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
99,13/07/2020 21:23:57,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No
100,18/07/2020 20:16:21,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No

In [22]:
frame=pd.DataFrame(x,columns=["Age","What is your course?","What is your CGPA?","Marital status"])

In [23]:
frame

     Age What is your course? What is your CGPA?  Marital status
0    NaN                  NaN                NaN            True
1    NaN                  NaN                NaN            True
2    NaN                  NaN                NaN            True
3    NaN                  NaN                NaN            True
4    NaN                  NaN                NaN            True
..   ...                  ...                ...             ...
96   NaN                  NaN                NaN            True
97   NaN                  NaN                NaN            True
98   NaN                  NaN                NaN            True
99   NaN                  NaN                NaN            True
100  NaN                  NaN                NaN            True

[101 rows x 4 columns]